// <auto-generated />
using System;
using Atlas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261006190604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.AccountDetailsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("AccountDetails", (string)null);
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.ApplicationDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("ApplicationDecisions", (string)null);
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Applications_CreatedAt");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Applications_Email");

                    b.HasIndex("MarketCode", "Status")
                        .HasDatabaseName("IX_Applications_MarketCode_Status");

                    b.ToTable("Applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Applications_MarketCode", "[MarketCode] IN ('MA', 'MB', 'MC', 'MD', 'ME', 'MF')");

                            t.HasCheckConstraint("CK_Applications_Status", "[Status] IN ('Pending', 'Approved', 'Rejected', 'PendingReview')");
                        });
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MarketCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_AuditLogs_ApplicationId");

                    b.HasIndex("MarketCode")
                        .HasDatabaseName("IX_AuditLogs_MarketCode");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.CardOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequiresBranchActivation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("CardOrders", (string)null);
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_Documents_ApplicationId");

                    b.ToTable("Documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Documents_Type", "[DocumentType] IN ('PASSPORT', 'ID_CARD', 'SELFIE')");
                        });
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.IdentityVerificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<string>("DocumentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("FaceMatch")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("IdentityVerifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentityVerifications_DocumentStatus", "[DocumentStatus] IN ('Valid', 'Invalid', 'Inconclusive')");
                        });
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.RejectionReasonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("RejectionReasons", (string)null);
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.SanctionMatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Score")
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<Guid>("ScreeningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningId");

                    b.ToTable("SanctionMatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_SanctionMatches_Type", "[MatchType] IN ('Sanctions', 'PEP')");
                        });
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.SanctionsScreeningEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ScreenedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("SanctionsScreenings", null, t =>
                        {
                            t.HasCheckConstraint("CK_SanctionsScreenings_Status", "[Status] IN ('Clear', 'PossibleMatch')");
                        });
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.AccountDetailsEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationEntity", "Application")
                        .WithOne("AccountDetails")
                        .HasForeignKey("Atlas.Infrastructure.Data.Entities.AccountDetailsEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.ApplicationDecisionEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationEntity", "Application")
                        .WithOne("Decision")
                        .HasForeignKey("Atlas.Infrastructure.Data.Entities.ApplicationDecisionEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationEntity", "Application")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.CardOrderEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationEntity", "Application")
                        .WithOne("CardOrder")
                        .HasForeignKey("Atlas.Infrastructure.Data.Entities.CardOrderEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.DocumentEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationEntity", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.IdentityVerificationEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationEntity", "Application")
                        .WithOne("IdentityVerification")
                        .HasForeignKey("Atlas.Infrastructure.Data.Entities.IdentityVerificationEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.RejectionReasonEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationDecisionEntity", "Decision")
                        .WithMany("RejectionReasons")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.SanctionMatchEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.SanctionsScreeningEntity", "Screening")
                        .WithMany("Matches")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.SanctionsScreeningEntity", b =>
                {
                    b.HasOne("Atlas.Infrastructure.Data.Entities.ApplicationEntity", "Application")
                        .WithOne("SanctionsScreening")
                        .HasForeignKey("Atlas.Infrastructure.Data.Entities.SanctionsScreeningEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.ApplicationDecisionEntity", b =>
                {
                    b.Navigation("RejectionReasons");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("AccountDetails");

                    b.Navigation("AuditLogs");

                    b.Navigation("CardOrder");

                    b.Navigation("Decision");

                    b.Navigation("Documents");

                    b.Navigation("IdentityVerification");

                    b.Navigation("SanctionsScreening");
                });

            modelBuilder.Entity("Atlas.Infrastructure.Data.Entities.SanctionsScreeningEntity", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
